title: Hackerspace Monterrey
url: http://hsmty.org
exclude: [README.md, LICENSE, Rakefile.rb, Gemfile, Gemfile.lock]
permalink: /blog/:year/:month/:title
timezone: America/Monterrey
encoding: UTF-8
markdown: redcarpet
pygments: false
future: false
paginate: 5
paginate_path: blog/:num
